### ISSUE TITLE
Rename project to be less inconsistent, be external to dib-lab/

### ISSUE THREAD

**Issue by ctb** [osfclient/osfclient#125]
Right now we have 'dib-lab/osf-cli' as the repo, `osfclient' as the pypi package, and `osf` as the command line.

I propose moving the project to `osfclient/osfclient`, keeping the pypi package `osfclient`, and keep the command line `osf`.

Thoughts?

**Comment by untzag** [comment]
for completeness there is also [osfclient on conda-forge](https://anaconda.org/conda-forge/osfclient)

**Comment by sloria** [comment]
@ctb +1 for consistency. There may, however, be a potential issue with then name `osfclient` if the underlying OSF API client gets separated into its own package. "osfclient" would be a more appropriate name for the API client than the CLI.

**Comment by ctb** [comment]
On Mon, Oct 16, 2017 at 07:16:57AM -0700, Steven Loria wrote:
> @ctb +1 for consistency. There may, however, be a potential issue with then name `osfclient` if the underlying OSF API client gets separated into its own package. "osfclient" would be a more appropriate name for the API client than the CLI.

I was thinking the same thing, but am not too worried about the consequences
of success (which this would be :).  Other suggestions welcome in any case -
it's clear that the current situation is just silly!

**Comment by betatim** [comment]
I'd suggest we move this repo to the https://github.com/osfclient organisation and rename it to "osfclient" as part of that move. In the past GitHub has been pretty smart in terms of putting the correct redirects in place so that old URLs continue to work.

---

Splitting the project into subprojects: I'd suggest creating a new issue to discuss that topic with the goal of hearing what people think about the idea, how to name things, etc

**Comment by ctb** [comment]
seems like no objections -- should we proceed with the move?

**Comment by betatim** [comment]
Moving now. Fasten your seatbelt and see you on the other side.

**Comment by betatim** [comment]
You can now find this repo at: https://github.com/osfclient/osfclient

You probably don't have to do anything with your local `git` setup but it also doesn't hurt to update your upstream remote to point to the new location.

**Comment by benlindsay** [comment]
I'm going to go out on a limb and close this one. Let me know if anyone wants this reopened for any reason.
