### ISSUE TITLE
Enable OAuth authentication (ORCID)

### ISSUE THREAD

**Issue by ksunden** [osfclient/osfclient#140]
OSF allows users to use OAuth via ORCID (or other institutional logins)
It would be nice to be able to authenticate against that rather than need an OSF specific login.

This is related to #101 and #99, though those seem to be aimed towards the tokens you can generate yourself rather than specifically OAuth.

**Comment by felliott** [comment]
@ksunden, the next release (v0.0.5) will support token-based auth.  You can create a token by going to your [Personal Access Tokens page](https://osf.io/settings/tokens) after logging in via ORCID.  I will close this PR when v0.0.5 is released (soon!)

**Comment by felliott** [comment]
This has been merged into `master` and released in `osfclient==0.0.5`. Thank you, @ksunden!
