### ISSUE TITLE
clone is not finding any files from public project 

### ISSUE THREAD

**Issue by crazyhottommy** [osfclient/osfclient#166]
Hi,

I installed `osfclient` by `pip`.
the test worked fine

```bash
osf -p fuqsk clone
```

but for this particular project it did not find any files
https://osf.io/b9hj5/

```
osf -p b9hj5  clone
0files [00:00, ?files/s]
```

Thank you for looking into it!
Tommy

**Comment by felliott** [comment]
Hey @crazyhottommy,

That project doesn't have any files, but it has a subcomponent (https://osf.io/t6nhm/) that does.  Try `osf -p t6nhm clone` and see if that works.

Cheers,
@felliott

**Comment by crazyhottommy** [comment]
@felliott thank you, that worked! I forked that project and did not realize the strange structure of folders.
