### ISSUE TITLE
add token option to client

### ISSUE THREAD

**Issue by genignored** [osfclient/osfclient#188]
it appears the the command line version of osf will only allow you to use username/password combos (or environment variables).  Is it possible to allow to point to a file with a token, as an alternative option?

**Comment by devinberg** [comment]
I believe this is related to #99 and #101 and maybe partially related to #140.

**Comment by felliott** [comment]
This should be fixed in the next release, which I am preparing now.

**Comment by felliott** [comment]
This has been merged into `master` and released in `osfclient==0.0.5`. Thank you, @genignored!
