### ISSUE TITLE
Unable to upload file into existing folder in OSF storage

### ISSUE THREAD

**Issue by billbrod** [osfclient/osfclient#199]
I recently discovered that I am unable to upload a file into an existing folder in OSF storage, which I used to be able to do (I assume this has something to do with the changes to file storage OSF has made recently?), as recently as May 2, 2022. This is all with version 0.0.5, installed via pip

I created a [new OSF project](https://osf.io/fh6kz/) to test this out. After creating the new project, I ran `osf init` and gave it my username and project name (`fh6kz`). I then created a small text file, `test.txt`, to test it with. `osf upload test.txt osfstorage/test.txt` ran without a problem, as did the first time I ran `osf upload test.txt osfstorage/new_dir/test.txt`. However, the second time I tried to run `osf upload test.txt osfstorage/new_dir/test.txt`, I received the following error:

```
Traceback (most recent call last):
  File "/home/billbrod/miniconda3/bin/osf", line 8, in <module>
    sys.exit(main())
  File "/home/billbrod/miniconda3/lib/python3.7/site-packages/osfclient/__main__.py", line 120, in main
    exit_code = args.func(args)
  File "/home/billbrod/miniconda3/lib/python3.7/site-packages/osfclient/cli.py", line 98, in wrapper
    return_value = f(cli_args)
  File "/home/billbrod/miniconda3/lib/python3.7/site-packages/osfclient/cli.py", line 326, in upload
    update=args.update)
  File "/home/billbrod/miniconda3/lib/python3.7/site-packages/osfclient/models/storage.py", line 78, in create_file
    parent = parent.create_folder(directory, exist_ok=True)
  File "/home/billbrod/miniconda3/lib/python3.7/site-packages/osfclient/models/file.py", line 149, in create_folder
    name))
RuntimeError: Response has status code 500 while creating folder new_dir.
```

so I assume it's trying to create the directory even though it's already there? Adding the `--force` flag doesn't solve the problem. Do you have any suggestions for how to fix the problem?

Thanks, this tool has been incredibly useful!

**Comment by JanaLasser** [comment]
I have a similar problem. I have a project in which I upload a file to OSF every hour. It broke on June 22 at 1:00 PM CEST. I also assume this has to do with the recent changes introduced to OSF.

**Comment by felliott** [comment]
Hello!

Thanks for reporting this.  You're both right, it was a bug I accidentally introduced in the most recent release. I've pushed up a fix for it, so osfclient should handle the conflict more gracefully.  @billbrod, if the `test.txt` file already exists, running the command as written will still produce an error, but it should be the (slightly) better named `FileExistsError`.  If you want to update the file with new contents, you'll need to add the `--update` or `-U` switch after the `upload` arg.  The new command should be:

**Comment by felliott** [comment]
(d'oh, hit enter too soon)

The new command should be:

```
osf upload -U test.txt osfstorage/new_dir/test.txt
```

Please let me know if this works for you! I'll go ahead and close the issue, but feel free to reopen if you run into any trouble. with it.

Thank you!
@felliott

**Comment by billbrod** [comment]
Thanks @felliott! I get the `FileExistsError` now, but when I run `osf upload -U test.txt osfstorage/new_dir/test.txt` I get a `FileNotFoundError` (I ran `pip install --upgrade osfclient` first, though I think I already had the most recent version on pip):

```
>> osf upload -U test.txt osfstorage/new_dir/test.txt 
Please input your password:
Traceback (most recent call last):
  File "/home/billbrod/miniconda3/envs/metamers/bin/osf", line 8, in <module>
    sys.exit(main())
  File "/home/billbrod/miniconda3/envs/metamers/lib/python3.7/site-packages/osfclient/__main__.py", line 120, in main
    exit_code = args.func(args)
  File "/home/billbrod/miniconda3/envs/metamers/lib/python3.7/site-packages/osfclient/cli.py", line 98, in wrapper
    return_value = f(cli_args)
  File "/home/billbrod/miniconda3/envs/metamers/lib/python3.7/site-packages/osfclient/cli.py", line 326, in upload
    update=args.update)
  File "/home/billbrod/miniconda3/envs/metamers/lib/python3.7/site-packages/osfclient/models/storage.py", line 120, in create_file
    if checksum(path) == file_.hashes.get('md5'):
  File "/home/billbrod/miniconda3/envs/metamers/lib/python3.7/site-packages/osfclient/utils.py", line 86, in checksum
    with open(file_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'new_dir/test.txt'
```

EDIT: However, now running `osf upload -f test.txt osfstorage/new_dir/test.txt` runs correctly, so I guess the problem is solved?

**Comment by felliott** [comment]
Looking into this, I think you've stumbled upon a different bug in `osfclient`.  It's trying to [compare the hashes of the local and remote file](https://github.com/osfclient/osfclient/blob/master/osfclient/models/storage.py#L120), but it's passing the remote path to the checksum function instead of the local path.  I didn't encounter this b/c my local and remote storages have identical structures. The `-f` switch avoids this by [bypassing the hash comparison](https://github.com/osfclient/osfclient/blob/master/osfclient/models/storage.py#L119).  As a workaround, you should be able to pass both `-f` and `-U` as switches to `upload` when you want to update a file, like so (switch order reversed for politeness's sake):

```
osf upload -Uf test.txt osfstorage/new_dir/test.txt
```

**Comment by billbrod** [comment]
That works, thanks!
